"""
Email Response Generator Module

Generates context-aware replies using OLLAMA LLM.
"""

import logging
from typing import Dict, Optional
from pydantic import BaseModel

logger = logging.getLogger(__name__)


class ResponseGenerationRequest(BaseModel):
    """Request model for response generation."""
    email_subject: str
    email_body: str
    sender: str
    classification_intent: str
    classification_summary: str
    include_action_items: bool = True


class ResponseGenerationResult(BaseModel):
    """Result model for generated response."""
    response_text: str
    response_tone: str
    length: int
    includes_action_items: bool
    error: Optional[str] = None


class ResponseGenerator:
    """Generates email responses using OLLAMA LLM."""
    
    def __init__(self, ollama_client, company_info: Dict = None):
        """
        Initialize response generator.
        
        Args:
            ollama_client: OLLAMAClient instance
            company_info: Dictionary with company details
        """
        self.ollama_client = ollama_client
        self.company_info = company_info or {
            "name": "Company",
            "support_email": "support@company.com"
        }
    
    async def generate(self, request: ResponseGenerationRequest) -> ResponseGenerationResult:
        """
        Generate response to email.
        
        Args:
            request: Response generation request
            
        Returns:
            Generated response result
        """
        try:
            logger.info(f"Generating response for: {request.email_subject[:50]}")
            
            email_dict = {
                "subject": request.email_subject,
                "body": request.email_body,
                "sender": request.sender
            }
            
            classification_dict = {
                "intent": request.classification_intent,
                "summary": request.classification_summary
            }
            
            # Generate response using OLLAMA
            response_text = await self.ollama_client.generate_response(
                email_dict,
                classification_dict
            )
            
            # Add signature
            signature = self._get_signature()
            full_response = f"{response_text}\n\n{signature}"
            
            result = ResponseGenerationResult(
                response_text=full_response,
                response_tone="professional",
                length=len(full_response),
                includes_action_items=request.include_action_items
            )
            
            logger.info(f"Response generated ({result.length} chars)")
            return result
        
        except Exception as e:
            logger.error(f"Response generation error: {e}")
            return ResponseGenerationResult(
                response_text="",
                response_tone="professional",
                length=0,
                includes_action_items=False,
                error=str(e)
            )
    
    async def batch_generate(self, requests: list) -> list:
        """
        Generate responses for multiple emails.
        
        Args:
            requests: List of response generation requests
            
        Returns:
            List of generated responses
        """
        try:
            logger.info(f"Batch generating {len(requests)} responses")
            
            results = []
            for request in requests:
                result = await self.generate(request)
                results.append(result)
            
            logger.info(f"Batch generation complete: {len(results)} responses")
            return results
        
        except Exception as e:
            logger.error(f"Batch generation error: {e}")
            return []
    
    def _get_signature(self) -> str:
        """Get email signature."""
        company = self.company_info.get("name", "Company")
        support_email = self.company_info.get("support_email", "support@company.com")
        
        return f"""---
Best regards,

{company} Support Team
{support_email}

This is an automated response generated by our AI Email Classification System."""
    
    async def customize_response(self, 
                                 base_response: str, 
                                 customization_prompt: str) -> str:
        """
        Customize a generated response with additional instructions.
        
        Args:
            base_response: Original generated response
            customization_prompt: Additional customization instructions
            
        Returns:
            Customized response text
        """
        try:
            logger.info("Customizing response")
            
            prompt = f"""Modify this email response according to the instructions:

Original Response:
{base_response}

Customization Instructions:
{customization_prompt}

Return the modified response only."""
            
            response = await self.ollama_client._call_ollama(prompt)
            logger.info("Response customization complete")
            return response
        
        except Exception as e:
            logger.error(f"Response customization error: {e}")
            return base_response
